/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


package Frames;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import proyect.pkg1.Funciones;
import proyect.pkg1.WeightList;
import proyect.pkg1.Grafo;


public class NewCargar extends javax.swing.JFrame {

    static Funciones fc;
    static WeightList lista;
    static Grafo mymatrix;
    public Inicio mywin;
    public File fichero;
    /**
     * Creates new form NewCargar
     */
    public NewCargar(Inicio mywin) {
        initComponents();
        fc = new Funciones();
        lista = new WeightList();
        this.mywin = mywin;
        initComponents();
        this.setLocationRelativeTo(null);
    }

 
    private NewCargar() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cerrar = new javax.swing.JButton();
        guardarTXT = new javax.swing.JButton();
        cargarTXT = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(484, 384));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cerrar.setFont(new java.awt.Font("Segoe UI Historic", 3, 18)); // NOI18N
        cerrar.setText("CERRAR");
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });
        getContentPane().add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 160, -1));

        guardarTXT.setFont(new java.awt.Font("Segoe UI Historic", 3, 18)); // NOI18N
        guardarTXT.setText("GUARDAR");
        guardarTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarTXTActionPerformed(evt);
            }
        });
        getContentPane().add(guardarTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 150, -1));

        cargarTXT.setFont(new java.awt.Font("Segoe UI Historic", 3, 18)); // NOI18N
        cargarTXT.setText("CARGAR ARCHIVO");
        cargarTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarTXTActionPerformed(evt);
            }
        });
        getContentPane().add(cargarTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Carga y Guardado de Archivos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/servidores.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        mywin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cerrarActionPerformed

    private void guardarTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarTXTActionPerformed
        try{
            mywin.setListaVersx(fc.Leer_matrix(fichero.getAbsolutePath()));
            mywin.setListaSimpe(fc.Leer_txt(fichero.getAbsolutePath(),mywin.listaVersx));
            Grafo  matrix=new Grafo (mywin.listaVersx,mywin.listaSimpe,mywin.listaVersx.getSize(),mywin.listaVersx.getSize());
            mywin.setMatrixre(matrix);
            Funciones funct=new Funciones();
            funct.writeTxt(mywin.listaVersx, mywin.listaSimpe);
        } catch(Exception e){
            JOptionPane.showMessageDialog(this, "ERROR!");
        };
    }//GEN-LAST:event_guardarTXTActionPerformed

    private void cargarTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarTXTActionPerformed
        JFileChooser fx = new JFileChooser();

        int seleccion = fx.showOpenDialog(this);

        if (seleccion == JFileChooser.APPROVE_OPTION) {

            fichero = fx.getSelectedFile();
            
            JOptionPane.showMessageDialog(null, "Debe guardar para mantener los cambios","ADVERTENCIA",JOptionPane.WARNING_MESSAGE);
        }

        try{
           
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "ERROR!");
        }
    }//GEN-LAST:event_cargarTXTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewCargar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewCargar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewCargar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewCargar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewCargar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cargarTXT;
    private javax.swing.JButton cerrar;
    private javax.swing.JButton guardarTXT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
